In [15]:
import pandas as pd

In [16]:
df=pd.read_csv('customers.csv')
df.head()

   customer_id   customer_name     city signup_date customer_segment
0            1    Vikram Patel  Kolkata  2023-04-18         Standard
1            2  Sanjay Agarwal    Kochi  2023-03-20         Standard
2            3    Ananya Gupta     Pune  2023-04-17         Standard
3            4   Ananya Sharma  Kolkata  2024-05-17           Budget
4            5    Sanjay Patel  Chennai  2026-05-08         Standard

In [17]:
df.tail()

     customer_id  customer_name        city signup_date customer_segment
495          496    Nisha Mehta   Ahmedabad  2023-10-21           Budget
496          497  Aditya Sharma   Ahmedabad  2023-05-18          Premium
497          498    Sneha Mehta     Chennai  2024-03-25         Standard
498          499     Amit Singh       Kochi  2024-06-27          Premium
499          500    Pooja Gupta  Coimbatore  2026-04-24         Standard

In [18]:
df.isnull().sum()

customer_id         0
customer_name       0
city                0
signup_date         0
customer_segment    0
dtype: int64

In [19]:
df.shape

(500, 5)

In [20]:
df.columns

Index(['customer_id', 'customer_name', 'city', 'signup_date',
       'customer_segment'],
      dtype='str')

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       500 non-null    int64
 1   customer_name     500 non-null    str
 2   city              500 non-null    str
 3   signup_date       500 non-null    str
 4   customer_segment  500 non-null    str
dtypes: int64(1), str(4)
memory usage: 19.7 KB

In [22]:
df.describe()

       customer_id
count   500.000000
mean    250.500000
std     144.481833
min       1.000000
25%     125.750000
50%     250.500000
75%     375.250000
max     500.000000

In [26]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

In [28]:
df.columns

Index(['customer_id', 'customer_name', 'city', 'signup_date',
       'customer_segment'],
      dtype='str')

In [31]:
df["signup_date"]=pd.to_datetime (df["signup_date"])

In [34]:
df.dtypes

customer_id                  int64
customer_name                  str
city                           str
signup_date         datetime64[us]
customer_segment               str
dtype: object

In [40]:
df.iloc[0:5,0:5]

   customer_id   customer_name     city signup_date customer_segment
0            1    Vikram Patel  Kolkata  2023-04-18         Standard
1            2  Sanjay Agarwal    Kochi  2023-03-20         Standard
2            3    Ananya Gupta     Pune  2023-04-17         Standard
3            4   Ananya Sharma  Kolkata  2024-05-17           Budget
4            5    Sanjay Patel  Chennai  2026-05-08         Standard

In [42]:
df.groupby("city")["customer_name"].count()

city
Ahmedabad     65
Bangalore     49
Chennai       45
Coimbatore    48
Delhi         58
Hyderabad     47
Kochi         50
Kolkata       41
Mumbai        50
Pune          47
Name: customer_name, dtype: int64

In [43]:
df["customer_name"].str.strip()

0        Vikram Patel
1      Sanjay Agarwal
2        Ananya Gupta
3       Ananya Sharma
4        Sanjay Patel
            ...
495       Nisha Mehta
496     Aditya Sharma
497       Sneha Mehta
498        Amit Singh
499       Pooja Gupta
Name: customer_name, Length: 500, dtype: str

In [46]:
df["customer_segment"].value_counts()

customer_segment
Standard    260
Budget      138
Premium     102
Name: count, dtype: int64