In [1]:
import pandas as pd

In [2]:
customers=pd.read_csv("customers.csv")
orders=pd.read_csv("orders.csv")
products=pd.read_csv("products.csv")
payments=pd.read_csv("payments.csv")
order_items=pd.read_csv("order_items.csv")

In [3]:
print("customers:",customers.shape)
print("orders:",orders.shape)
print("products:",products.shape)
print("payment:",payments.shape)
print("order_items:",order_items.shape)

customers: (500, 5)
orders: (3000, 6)
products: (50, 5)
payment: (3000, 3)
order_items: (5325, 5)

In [4]:
customers.head()

   customer_id   customer_name     city signup_date customer_segment
0            1    Vikram Patel  Kolkata  2023-04-18         Standard
1            2  Sanjay Agarwal    Kochi  2023-03-20         Standard
2            3    Ananya Gupta     Pune  2023-04-17         Standard
3            4   Ananya Sharma  Kolkata  2024-05-17           Budget
4            5    Sanjay Patel  Chennai  2026-05-08         Standard

In [5]:
orders.head()

,order_id,customer_id,order_date,order_status,payment_method,discount_amount
0,10001,108,2025-09-19,Completed,Credit Card,100
1,10002,122,2024-11-24,Pending,Net Banking,750
2,10003,293,2026-03-07,Completed,Wallet,50
3,10004,105,2024-01-19,Completed,Credit Card,50
4,10005,230,2024-03-24,Completed,Wallet,50

In [6]:
products.head()

   product_id       product_name     category  unit_price  cost_price
0         101             Laptop  Electronics       65000       52000
1         102         Smartphone  Electronics       30000       24000
2         103             Tablet  Electronics       18000       14000
3         104         Smartwatch  Electronics        6500        4200
4         105  Bluetooth Speaker  Electronics        3500        2200

In [7]:
payments.head()

   order_id payment_method payment_status
0     10001    Credit Card        Success
1     10002    Net Banking        Pending
2     10003         Wallet        Success
3     10004    Credit Card        Success
4     10005         Wallet        Success

In [8]:
order_items.head()

   order_item_id  order_id  product_id  quantity  selling_price
0              1     10001         105         1         3500.0
1              2     10001         114         2         6300.0
2              3     10001         141         1        38000.0
3              4     10002         122         1         1764.0
4              5     10003         133         3          250.0

In [9]:
customers.isnull().sum()

customer_id         0
customer_name       0
city                0
signup_date         0
customer_segment    0
dtype: int64

In [10]:
products.isnull().sum()

product_id      0
product_name    0
category        0
unit_price      0
cost_price      0
dtype: int64

In [11]:
orders.isnull().sum()

order_id           0
customer_id        0
order_date         0
order_status       0
payment_method     0
discount_amount    0
dtype: int64

In [12]:
order_items.isnull().sum()

order_item_id    0
order_id         0
product_id       0
quantity         0
selling_price    0
dtype: int64

In [13]:
payments.isnull().sum()

order_id          0
payment_method    0
payment_status    0
dtype: int64

In [14]:
customers.duplicated().sum()

np.int64(0)

In [15]:
orders.duplicated().sum()

np.int64(0)

In [16]:
products.duplicated().sum()

np.int64(0)

In [17]:
order_items.duplicated().sum()

np.int64(0)

In [18]:
payments.duplicated().sum()

np.int64(0)

In [19]:
customers.dtypes

customer_id         int64
customer_name         str
city                  str
signup_date           str
customer_segment      str
dtype: object

In [20]:
customers["signup_date"]=pd.to_datetime(customers["signup_date"])

In [21]:
products.dtypes

product_id      int64
product_name      str
category          str
unit_price      int64
cost_price      int64
dtype: object

In [22]:
orders.dtypes

order_id           int64
customer_id        int64
order_date           str
order_status         str
payment_method       str
discount_amount    int64
dtype: object

In [23]:
orders["order_date"]=pd.to_datetime(orders["order_date"])

In [24]:
order_items.dtypes

order_item_id      int64
order_id           int64
product_id         int64
quantity           int64
selling_price    float64
dtype: object

In [25]:
payments.dtypes

order_id          int64
payment_method      str
payment_status      str
dtype: object

In [26]:
orders.head()

,order_id,customer_id,order_date,order_status,payment_method,discount_amount
0,10001,108,2025-09-19,Completed,Credit Card,100
1,10002,122,2024-11-24,Pending,Net Banking,750
2,10003,293,2026-03-07,Completed,Wallet,50
3,10004,105,2024-01-19,Completed,Credit Card,50
4,10005,230,2024-03-24,Completed,Wallet,50

In [27]:
orders["order_status"].value_counts()

order_status
Completed    2437
Cancelled     243
Returned      179
Pending       141
Name: count, dtype: int64

In [28]:
customers["customer_segment"].value_counts()

customer_segment
Standard    260
Budget      138
Premium     102
Name: count, dtype: int64

In [29]:
products[["unit_price", "cost_price"]].describe()

         unit_price    cost_price
count     50.000000     50.000000
mean    7413.000000   5436.800000
std    12602.234212  10167.230362
min      250.000000    100.000000
25%     1650.000000    925.000000
50%     2900.000000   1800.000000
75%     5375.000000   3525.000000
max    65000.000000  52000.000000

In [30]:
order_items[["quantity", "selling_price"]].describe()

          quantity  selling_price
count  5325.000000    5325.000000
mean      1.772019    7025.781878
std       1.025706   12164.513394
min       1.000000     225.000000
25%       1.000000    1568.000000
50%       1.000000    2744.000000
75%       2.000000    5000.000000
max       5.000000   65000.000000

In [31]:
customers["customer_name"] = customers["customer_name"].str.strip()
customers["city"] = customers["city"].str.strip()
customers["customer_segment"] = customers["customer_segment"].str.strip()

In [32]:
products["product_name"] = products["product_name"].str.strip()
products["category"] = products["category"].str.strip()

In [33]:
payments["payment_method"] = payments["payment_method"].str.strip()
payments["payment_status"] = payments["payment_status"].str.strip()

In [34]:
print("Customers:")
print(customers.isnull().sum())

print("\nProducts:")
print(products.isnull().sum())

print("\nOrders:")
print(orders.isnull().sum())

print("\nOrder Items:")
print(order_items.isnull().sum())

print("\nPayments:")
print(payments.isnull().sum())

Customers:
customer_id         0
customer_name       0
city                0
signup_date         0
customer_segment    0
dtype: int64

Products:
product_id      0
product_name    0
category        0
unit_price      0
cost_price      0
dtype: int64

Orders:
order_id           0
customer_id        0
order_date         0
order_status       0
payment_method     0
discount_amount    0
dtype: int64

Order Items:
order_item_id    0
order_id         0
product_id       0
quantity         0
selling_price    0
dtype: int64

Payments:
order_id          0
payment_method    0
payment_status    0
dtype: int64

In [35]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [36]:
(products["unit_price"] <= 0).sum()

np.int64(0)

In [37]:
(products["cost_price"] <= 0).sum()

np.int64(0)

In [38]:
(order_items["quantity"] <= 0).sum()

np.int64(0)

In [39]:
(order_items["selling_price"] <= 0).sum()

np.int64(0)

In [40]:
orders["customer_id"].isin(
    customers["customer_id"]
).sum()

np.int64(3000)

In [41]:
order_items["order_id"].isin(
    orders["order_id"]
).sum()

np.int64(5325)

In [42]:
order_items["product_id"].isin(
    products["product_id"]
).sum()

np.int64(5325)

In [43]:
len(order_items)

5325

In [44]:
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Payments:", payments.shape)

Customers: (500, 5)
Products: (50, 5)
Orders: (3000, 6)
Order Items: (5325, 5)
Payments: (3000, 3)

customer Analysis:
How many customers are in each segment?

In [45]:
customers["customer_segment"].value_counts()

customer_segment
Standard    260
Budget      138
Premium     102
Name: count, dtype: int64

Which city has the most customers?

In [46]:
customers["city"].value_counts()

city
Ahmedabad     65
Delhi         58
Kochi         50
Mumbai        50
Bangalore     49
Coimbatore    48
Pune          47
Hyderabad     47
Chennai       45
Kolkata       41
Name: count, dtype: int64

How many different cities are there?

In [47]:
customers["city"].nunique()

10

Order Analysis:
Which order status has the highest number of orders?

In [48]:
orders["order_status"].value_counts().idxmax()

'Completed'

Payment Analysis:
Which payment method is most commonly used?

In [49]:
payments["payment_method"].value_counts().idxmax()

'Net Banking'

Product Analysis:
Number of products
Which category contains the most products?

In [50]:
len(products)

50

In [51]:
products["category"].value_counts()

category
Electronics        8
Home Appliances    8
Fashion            7
Accessories        6
Beauty             5
Sports             5
Furniture          3
Kitchen            3
Stationery         3
Home & Living      2
Name: count, dtype: int64

In [52]:
products["category"].value_counts().idxmax()

'Electronics'

Order Items Analysis:
Total units sold
Average quantity per item record
Highest quantity in one item record

In [53]:
order_items["quantity"].sum()

np.int64(9436)

In [54]:
order_items["quantity"].mean()

np.float64(1.772018779342723)

In [55]:
order_items["quantity"].max()

np.int64(5)

In [56]:
order_customer = orders.merge(
    customers,
    on="customer_id",
    how="inner"
)

order_customer.head()

,order_id,customer_id,order_date,order_status,payment_method,discount_amount,customer_name,city,signup_date,customer_segment
0,10001,108,2025-09-19,Completed,Credit Card,100,Sanjay Rao,Delhi,2025-06-22,Budget
1,10002,122,2024-11-24,Pending,Net Banking,750,Sneha Verma,Kolkata,2025-12-11,Budget
2,10003,293,2026-03-07,Completed,Wallet,50,Nisha Gupta,Mumbai,2023-02-15,Premium
3,10004,105,2024-01-19,Completed,Credit Card,50,Sneha Agarwal,Mumbai,2026-02-08,Budget
4,10005,230,2024-03-24,Completed,Wallet,50,Sneha Reddy,Bangalore,2024-11-25,Budget

In [57]:
order_products = order_items.merge(products,on="product_id",how="inner")
order_products.head()

,order_item_id,order_id,product_id,quantity,selling_price,product_name,category,unit_price,cost_price
0,1,10001,105,1,3500.0,Bluetooth Speaker,Electronics,3500,2200
1,2,10001,114,2,6300.0,Study Table,Furniture,7000,4800
2,3,10001,141,1,38000.0,LED TV,Electronics,38000,30000
3,4,10002,122,1,1764.0,Casual Shirt,Fashion,1800,1000
4,5,10003,133,3,250.0,Notebook,Stationery,250,100

In [58]:
order_details=order_customer.merge(order_products,on="order_id",how="inner")
order_details.head()

,order_id,customer_id,order_date,order_status,payment_method,discount_amount,customer_name,city,signup_date,customer_segment,order_item_id,product_id,quantity,selling_price,product_name,category,unit_price,cost_price
0,10001,108,2025-09-19,Completed,Credit Card,100,Sanjay Rao,Delhi,2025-06-22,Budget,1,105,1,3500.0,Bluetooth Speaker,Electronics,3500,2200
1,10001,108,2025-09-19,Completed,Credit Card,100,Sanjay Rao,Delhi,2025-06-22,Budget,2,114,2,6300.0,Study Table,Furniture,7000,4800
2,10001,108,2025-09-19,Completed,Credit Card,100,Sanjay Rao,Delhi,2025-06-22,Budget,3,141,1,38000.0,LED TV,Electronics,38000,30000
3,10002,122,2024-11-24,Pending,Net Banking,750,Sneha Verma,Kolkata,2025-12-11,Budget,4,122,1,1764.0,Casual Shirt,Fashion,1800,1000
4,10003,293,2026-03-07,Completed,Wallet,50,Nisha Gupta,Mumbai,2023-02-15,Premium,5,133,3,250.0,Notebook,Stationery,250,100

In [59]:
order_details=order_details.merge(payments,on="order_id",how="inner")
order_details.head()

,order_id,customer_id,order_date,order_status,payment_method_x,discount_amount,customer_name,city,signup_date,customer_segment,order_item_id,product_id,quantity,selling_price,product_name,category,unit_price,cost_price,payment_method_y,payment_status
0,10001,108,2025-09-19,Completed,Credit Card,100,Sanjay Rao,Delhi,2025-06-22,Budget,1,105,1,3500.0,Bluetooth Speaker,Electronics,3500,2200,Credit Card,Success
1,10001,108,2025-09-19,Completed,Credit Card,100,Sanjay Rao,Delhi,2025-06-22,Budget,2,114,2,6300.0,Study Table,Furniture,7000,4800,Credit Card,Success
2,10001,108,2025-09-19,Completed,Credit Card,100,Sanjay Rao,Delhi,2025-06-22,Budget,3,141,1,38000.0,LED TV,Electronics,38000,30000,Credit Card,Success
3,10002,122,2024-11-24,Pending,Net Banking,750,Sneha Verma,Kolkata,2025-12-11,Budget,4,122,1,1764.0,Casual Shirt,Fashion,1800,1000,Net Banking,Pending
4,10003,293,2026-03-07,Completed,Wallet,50,Nisha Gupta,Mumbai,2023-02-15,Premium,5,133,3,250.0,Notebook,Stationery,250,100,Wallet,Success

Sales & Revenue Analysis:
What is the total revenue?

In [60]:
order_details["Revenue"]=order_details["quantity"]*order_details["selling_price"]

In [61]:
total_revenue=order_details["Revenue"].sum()

In [62]:
print(total_revenue)

66170239.0

Which product generates the highest revenue?

In [63]:
product_revenue=order_details.groupby("product_name")["Revenue"].sum()
product_revenue=product_revenue.sort_values(ascending=False)
product_revenue.head(1)

product_name
Laptop    13464100.0
Name: Revenue, dtype: float64

Which category generates the highest revenue?

In [64]:
category_revenue=order_details.groupby("category")["Revenue"].sum()
category_revenue = category_revenue.sort_values(ascending=False)

category_revenue.head(1)

category
Electronics    32160783.0
Name: Revenue, dtype: float64

Which city generates the highest revenue?

In [65]:
city_revenue=order_details.groupby("city")["Revenue"].sum()
city_revenue=city_revenue.sort_values(ascending=False)
city_revenue.head(1)

city
Delhi    9250899.0
Name: Revenue, dtype: float64

Which customer segment generates the highest revenue?

In [66]:
customersegments_revenue=order_details.groupby("customer_segment")["Revenue"].sum()
customersegments_revenue=customersegments_revenue.sort_values(ascending=False)
customersegments_revenue.head(1)

customer_segment
Standard    36148438.5
Name: Revenue, dtype: float64

Which payment method generates the highest revenue?

In [67]:
payments_revenue=order_details.groupby("payment_method")["Revenue"].sum()
payments_revenue=payments_revenue.sort_values(ascending=False)
payments_revenue.head(1)

KeyError: 'payment_method'

Which month has the highest revenue?

In [ ]:
order_details["Month"]=order_details["order_date"].dt.to_period("M")

In [ ]:
Month_revenue=order_details.groupby("Month")["Revenue"].sum()
Month_revenue=Month_revenue.sort_values(ascending=False)
Month_revenue.head(1)

Month
2025-12    3263945.5
Freq: M, Name: Revenue, dtype: float64

Which product has the highest quantity sold?

In [ ]:
product_quantity = order_details.groupby("product_name")["quantity"].sum()
product_quantity=product_quantity.sort_values(ascending=False)
product_quantity.head(1)

product_name
Casual Shirt    238
Name: quantity, dtype: int64

Which category has the highest quantity sold?

In [ ]:
category_quantity = order_details.groupby("category")["quantity"].sum()

category_quantity = category_quantity.sort_values(ascending=False)

category_quantity.head(1)

category
Electronics    1445
Name: quantity, dtype: int64

What is the average order value (AOV)?

In [ ]:
order_revenue = order_details.groupby("order_id")["Revenue"].sum()
AOV = order_revenue.mean()

print(AOV)

22056.746333333333

Who are the Top 5 Customers by Revenue?

In [ ]:
customer_revenue = order_details.groupby("customer_name")["Revenue"].sum()

customer_revenue.sort_values(ascending=False).head(5)

customer_name
Arjun Bose       849919.0
Nisha Agarwal    831427.0
Kavya Gupta      790744.0
Priya Mishra     776088.5
Amit Kumar       740553.0
Name: Revenue, dtype: float64

How many Repeat Customers are there?

In [ ]:
customer_orders = order_details.groupby("customer_id")["order_id"].nunique()

repeat_customers = (customer_orders > 1).sum()

print(repeat_customers)

495

What is the Average Number of Items per Order?

In [ ]:
order_quantity = order_details.groupby("order_id")["quantity"].sum()

average_items_per_order = order_quantity.mean()

print(average_items_per_order)

3.1453333333333333

Which Product Generates the Highest Profit?

In [ ]:
order_details["Profit"] = (
    order_details["quantity"] *
    (order_details["selling_price"] - order_details["cost_price"])
)

In [ ]:
product_profit = order_details.groupby("product_name")["Profit"].sum()

product_profit.sort_values(ascending=False).head(1)

product_name
Laptop    2440100.0
Name: Profit, dtype: float64

Which Category Generates the Highest Profit?

In [ ]:
category_profit = order_details.groupby("category")["Profit"].sum()

category_profit.sort_values(ascending=False).head(1)

category
Electronics    6462183.0
Name: Profit, dtype: float64

In [ ]:
import pymysql
print("PyMySQL is working")

PyMySQL is working

In [ ]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:1234@localhost:3306/ecommerce_db"
)

print("Connected successfully")

Connected successfully

In [ ]:
customers.to_sql("customers", con=engine, if_exists="replace", index=False)

products.to_sql("products", con=engine, if_exists="replace", index=False)

orders.to_sql("orders", con=engine, if_exists="replace", index=False)

order_items.to_sql("order_items", con=engine, if_exists="replace", index=False)

payments.to_sql("payments", con=engine, if_exists="replace", index=False)

print("All 5 tables uploaded successfully")

All 5 tables uploaded successfully